version: '3'

tasks:

  add-and-translate-category:
    desc: |
      ➕ Add new category (with English translation), auto-translate to all other languages
    summary: |
      Add a new category with English translation and auto-translate it to all supported languages. Updates the file only on success.

      Example:
        TITLE="Pronouns" task add-and-translate-category
    cmds:
      - python3 scripts/add_category_and_translate.py --title "{{.TITLE}}" --file "{{.FILE}}"
    vars:
      FILE: ./resources/word.json
    requires:
      vars: [TITLE]

  translate-category:
    desc: |
      🌐 Translate existing category (based on English) to all supported languages
    cmds:
      - python3 scripts/category/translate_category.py --id "{{.CATEGORY_ID}}" --file "{{.FILE}}"
    vars:
      FILE: ./resources/word.json
    requires:
      vars: [CATEGORY_ID]

  add-category:
    desc: ➕ Add a new category and return its UUID
    cmds:
      - python3 scripts/category/add_category.py --title "{{.TITLE}}" --file "{{.FILE}}"
    vars:
      FILE: ./resources/word.json
    requires:
      vars: [TITLE]
